
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# This command is needed so that the working directory effectively is the same
# as `main.R`
# Change as needed
knitr::opts_knit$set(root.dir = "/Users/michaelhymowitz/Desktop/Grad Year/Stats 506/Stats 506 Final Project/group-13-stats-506-final-project")
```

This file documents the exploratory data analysis process undertaken before modeling was completed for this assignment.

```{r warning=FALSE, message=FALSE, results = "hide"}
source("src/environment_setup/imports_options_constants.R")
source("src/environment_setup/helper_funcs.R")
source("src/data_collection_and_cleaning/reading_and_cleaning_data.R")
```

# 1) Shape of fire dataset

```{r}
# Percentage of missing values per column in fire dataset
colMeans(is.na(fires_small))
```

```{r}
# Summary statistics of each column in fire dataset
fires_small_skimmed <- fires_small %>%
    skim_without_charts() %>%
    partition()
```

```{r}
# Summary statistics of character columns
fires_small_skimmed %>%
    .$character %>%
    as_tibble()
```

```{r}
# Summary statistics of numeric columns
fires_small_skimmed %>%
    .$numeric %>%
    as_tibble()
```

\newpage

# 2) Location of fires in United States

```{r fig.width=15, fig.height=10}
# Map of fire locations in United States
ggplot() +
    geom_polygon(data = county_locs,
                 aes(x = long, y = lat, group = group),
                 color = "darkgreen", fill = "lightgreen", size = 1) +
    geom_polygon(data = state_locs,
                 aes(x = long, y = lat, group = group),
                 color = "black", fill = "lightblue", size = 1, alpha = 0.3) +
    geom_point(data = fires_small,
               aes(x = longitude, y = latitude, color = log10(fire_size)), size = 0.1) +
    labs(title = "Fires in Continental United States, 1992-2015",
         x = "Longitude",
         y = "Latitude")
```

\newpage

# 3) Plots concerning makeup of each county

```{r fight.width=8, fig.height=8}
# Population of each county
ggplot() +
    geom_sf(data = us_county_data, aes(fill = log10(population + 1))) +
    scale_fill_viridis_c(option = "plasma") +
    labs(title = "Population (log) of Continental US Counties",
         x = "Longitude",
         y = "Latitude")
```

\newpage

```{r fight.width=8, fig.height=8}
# Per capita income of each county
ggplot() +
    geom_sf(data = us_county_data, aes(fill = log10(per_capita_income + 1))) +
    scale_fill_viridis_c(option = "plasma") +
    labs(title = "Per Capita Income (log) of Continental US Counties",
         x = "Longitude",
         y = "Latitude")
```

\newpage

# 4) Exploring modeling dataset

```{r}
# Univariate summary stats of each variable
mod_df_pre_eda %>%
    skim_without_charts() %>%
    partition() %>%
    .$numeric %>%
    as_tibble()
```

\newpage

```{r fig.width = 15, fig.height = 20}
# Univariate distribution of each variable
mod_df_pre_eda %>%
    inspect_num() %>%
    show_plot(col_palette = 2) +
    labs(title = "Histograms of Numeric Columns",
         x = "Variable Value")
```

\newpage

```{r}
# Transforming specified variables to bring all predictors and response to a
# roughly symmetric distribution
vars_to_log_transform <- c("num_fires",
                           "number_of_households",
                           "population",
                           "total_18_years_and_over",
                           "total_family_households",
                           "total_household_has_three_or_more_generations",
                           "total_male",
                           "total_owner_occupied",
                           "total_population_of_one_race",
                           "total_population_of_one_race_white_alone",
                           "total_races_tallied",
                           "total_races_tallied_for_householders",
                           "total_renter_occupied",
                           "total_two_or_more_races",
                           "total_under_18_years")

# mod_df is the final modeling dataframe
mod_df <- mod_df_pre_eda %>%
    mutate(across(all_of(vars_to_log_transform),
                  function(col) log10(col + 1),
                  .names = "{.col}_log")) %>%
    select(-all_of(vars_to_log_transform))

mod_df %>%
    glimpse()
```

\newpage

```{r fig.width = 15, fig.height = 20}
# Univariate distribution of each variable
mod_df %>%
    inspect_num() %>%
    show_plot(col_palette = 2) +
    labs(title = "Histograms of Numeric Columns",
         x = "Variable Value")
```

\newpage

```{r}
# Correlation between each predictor and `num_fires`
mod_df %>%
    select(-geoid) %>%
    cor() %>%
    as.data.frame() %>%
    rownames_to_column(var = "predictor") %>%
    as_tibble() %>%
    mutate(response = "num_fires_log") %>%
    filter(predictor != "num_fires_log") %>%
    select(response, predictor, num_fires_log) %>%
    rename(cor = num_fires_log) %>%
    arrange(desc(abs(cor)))
```

```{r fig.width = 12, fig.height = 15}
# Plotting multivariate relationship between each predictor and num_fires_log
mod_df %>%
    select(geoid, num_fires_log, everything()) %>%
    pivot_longer(cols = average_household_size_total:total_under_18_years_log,
                 names_to = "predictor",
                 values_to = "predictor_val") %>%
    ggplot(aes(x = predictor_val, y = num_fires_log)) +
    geom_point() +
    geom_smooth() +
    facet_wrap(~predictor, scale = "free_x", ncol = 4) +
    labs(title = "Bivariate Relationship between log10(Number of Fires per County) and all Predictors",
         x = "Value of Predictor",
         y = "# Fires (log)")
```

